// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbFwj7WY8mowVMiYetaNcVxgTnqTfjUs',
    appId: '1:16672326168:web:2d58de5401f42533d3b96d',
    messagingSenderId: '16672326168',
    projectId: 'bookme-8ca55',
    authDomain: 'bookme-8ca55.firebaseapp.com',
    storageBucket: 'bookme-8ca55.firebasestorage.app',
    measurementId: 'G-QE4F1W95T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TTkN6EmuIB90ayPxzx7o3urnUKkBA14',
    appId: '1:16672326168:android:2e134ffe9b2aee4cd3b96d',
    messagingSenderId: '16672326168',
    projectId: 'bookme-8ca55',
    storageBucket: 'bookme-8ca55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdP5RAF2SQyz58hTgOZbZJ6Nj1f-vhsig',
    appId: '1:16672326168:ios:2a4d3caa91ba7977d3b96d',
    messagingSenderId: '16672326168',
    projectId: 'bookme-8ca55',
    storageBucket: 'bookme-8ca55.firebasestorage.app',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdP5RAF2SQyz58hTgOZbZJ6Nj1f-vhsig',
    appId: '1:16672326168:ios:2a4d3caa91ba7977d3b96d',
    messagingSenderId: '16672326168',
    projectId: 'bookme-8ca55',
    storageBucket: 'bookme-8ca55.firebasestorage.app',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUbFwj7WY8mowVMiYetaNcVxgTnqTfjUs',
    appId: '1:16672326168:web:a13537ac9f7a84d2d3b96d',
    messagingSenderId: '16672326168',
    projectId: 'bookme-8ca55',
    authDomain: 'bookme-8ca55.firebaseapp.com',
    storageBucket: 'bookme-8ca55.firebasestorage.app',
    measurementId: 'G-GY8E20CFR1',
  );
}
